/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneosRouteImport } from './routes/torneos'
import { Route as SalonRouteImport } from './routes/salon'
import { Route as MultimediaRouteImport } from './routes/multimedia'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AnunciosRouteImport } from './routes/anuncios'
import { Route as IndexRouteImport } from './routes/index'

const TorneosRoute = TorneosRouteImport.update({
  id: '/torneos',
  path: '/torneos',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonRoute = SalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const MultimediaRoute = MultimediaRouteImport.update({
  id: '/multimedia',
  path: '/multimedia',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosRoute = AnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/calendario': typeof CalendarioRoute
  '/multimedia': typeof MultimediaRoute
  '/salon': typeof SalonRoute
  '/torneos': typeof TorneosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/calendario': typeof CalendarioRoute
  '/multimedia': typeof MultimediaRoute
  '/salon': typeof SalonRoute
  '/torneos': typeof TorneosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRoute
  '/calendario': typeof CalendarioRoute
  '/multimedia': typeof MultimediaRoute
  '/salon': typeof SalonRoute
  '/torneos': typeof TorneosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/anuncios' | '/calendario' | '/multimedia' | '/salon' | '/torneos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anuncios' | '/calendario' | '/multimedia' | '/salon' | '/torneos'
  id:
    | '__root__'
    | '/'
    | '/anuncios'
    | '/calendario'
    | '/multimedia'
    | '/salon'
    | '/torneos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciosRoute: typeof AnunciosRoute
  CalendarioRoute: typeof CalendarioRoute
  MultimediaRoute: typeof MultimediaRoute
  SalonRoute: typeof SalonRoute
  TorneosRoute: typeof TorneosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneos': {
      id: '/torneos'
      path: '/torneos'
      fullPath: '/torneos'
      preLoaderRoute: typeof TorneosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon': {
      id: '/salon'
      path: '/salon'
      fullPath: '/salon'
      preLoaderRoute: typeof SalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multimedia': {
      id: '/multimedia'
      path: '/multimedia'
      fullPath: '/multimedia'
      preLoaderRoute: typeof MultimediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios': {
      id: '/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciosRoute: AnunciosRoute,
  CalendarioRoute: CalendarioRoute,
  MultimediaRoute: MultimediaRoute,
  SalonRoute: SalonRoute,
  TorneosRoute: TorneosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
